### ISSUE TITLE
Can't reset password on admin account.

### ISSUE THREAD

**Issue by cwilsonIteris** [aws-samples/amazon-connect-contact-surveys#12]
I want to see if there's another way this can be accomplished? I just want to ensure that my account will be able to be recovered if a password is forgotten/lost.

![Screenshot 2024-01-03 at 3 27 07 PM](https://github.com/aws-samples/amazon-connect-contact-surveys/assets/155582780/437ef8b8-3e84-409c-98cb-f83e54245c45)

**Comment by aurelienaws** [comment]
Hi cwilsonIteris,
There is a pending commit to auto-verify the email address when deploying the stack. Currently, the email address is not auto-verified and that prevents the "forgot my password" flow to execute successfully (as per your comment). In the meantime, you can manually verify the email address by following the instructions found here : https://repost.aws/knowledge-center/cognito-confirm-account

The update to the project should be available in the next few days and will include other features, so you might be interested in redeploying the project once updated. I'll leave this issue opened for now, as it is a valid issue, and close it once the update is released.
Thanks for your support and feedback!

**Comment by aurelienaws** [comment]
This is now fixed. Please update your deployment with the latest Cloudformation template.
