### ISSUE TITLE
Chat only works for first question 

### ISSUE THREAD

**Issue by kannanrk85** [aws-samples/amazon-connect-contact-surveys#16]
Chat only works for the first question and ends after first response. Voice is working as charm without any issues.

**Comment by aurelienaws** [comment]
See - https://github.com/aws-samples/amazon-connect-contact-surveys/issues/14#issuecomment-2065479824

Please indicate what language is used in your Amazon Connect Flow when you invoke the survey module. Troubleshooting should point out that the Lex locale used is en_US. If you use are using a different locale in Amazon Connect, the bot will fail to match it.
See: https://docs.aws.amazon.com/connect/latest/adminguide/set-voice.html#set-voice-lexv2bot
