### ISSUE TITLE
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2022/12/20/[$LATEST]aac99eb749e045cca74aa7ee64de5294 (RequestId: 07277a4e-f86d-45e7-8bc9-f719a5f38def)

### ISSUE THREAD

**Issue by ZainGillani66** [aws-samples/amazon-connect-contact-surveys#4]
Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2022/12/20/[$LATEST]aac99eb749e045cca74aa7ee64de5294 (RequestId: 07277a4e-f86d-45e7-8bc9-f719a5f38def)

![image](https://user-images.githubusercontent.com/88433198/208725476-e81e8143-c86d-4a70-834d-ca0f5e2c0d6c.png)

![image](https://user-images.githubusercontent.com/88433198/208725620-5a3d38bb-c580-41cd-b655-bdf9d1399536.png)

**Comment by aurelienaws** [comment]
Hi there.
From the error posted, it seems that the steps for deployment where not followed correctly. Can you confirm that the S3 bucket to which you have uploaded the assets contains at the root:
- uuid-layer.zip
- the "frontend" folder (with its content as provided)

Thanks.

**Comment by aurelienaws** [comment]
Cannot reproduce.
